apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-app
  labels:
    app: demo-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ArgoCD Demo App</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                margin: 0; 
                padding: 40px; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                min-height: 100vh;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
            }
            .container {
                text-align: center;
                background: rgba(255,255,255,0.1);
                padding: 40px;
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0,0,0,0.1);
                max-width: 600px;
            }
            h1 { margin-bottom: 20px; font-size: 2.5em; }
            .info-box {
                background: rgba(255,255,255,0.2);
                padding: 20px;
                border-radius: 10px;
                margin: 20px 0;
                text-align: left;
            }
            .btn {
                background: #4CAF50;
                color: white;
                padding: 12px 24px;
                border: none;
                border-radius: 6px;
                cursor: pointer;
                font-size: 16px;
                margin: 10px;
                text-decoration: none;
                display: inline-block;
            }
            .btn:hover { background: #45a049; }
            .status { color: #4CAF50; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 ArgoCD Demo App</h1>
            <p><strong>GitOps in Action!</strong></p>
            <p>Diese App wird automatisch von ArgoCD synchronisiert!</p>
            
            <div class="info-box">
                <strong>Version:</strong> 1.0.0<br>
                <strong>Environment:</strong> Kubernetes<br>
                <strong>Deployed via:</strong> ArgoCD GitOps<br>
                <strong>Status:</strong> <span class="status">✅ Running</span><br>
                <strong>Zeit:</strong> <script>document.write(new Date().toLocaleString('de-DE'))</script>
            </div>
            
            <div class="info-box">
                <h3>🔄 GitOps Test Schritte:</h3>
                <ol style="text-align: left;">
                    <li>Ändern Sie diese HTML-Datei in Git</li>
                    <li>Committen und pushen Sie die Änderungen</li>
                    <li>ArgoCD erkennt die Änderungen automatisch</li>
                    <li>Die App wird automatisch aktualisiert</li>
                </ol>
            </div>
            
            <p>🎯 <strong>Nächster Schritt:</strong> Ändern Sie den Text oben und pushen Sie zu Git!</p>
        </div>
    </body>
    </html>
